# https://kubernetes.io/docs/concepts/configuration/configmap/
apiVersion: v1
kind: ConfigMap
metadata:
  name: quoty-test-configmap
data:
  PORT: "8000"  
  SNIPPETS_FILE: "./src/snippets.txt"
  MAX_REQUESTS_PER_MINUTE: "10"
---

